version: 2

models:



  - name: stg_prices
    description: Weekly product prices

    columns:
      - name: item_id
        tests:
          - not_null

      - name: store_id
        tests:
          - not_null

      - name: week_id
        tests:
          - not_null


  - name: stg_calendar
    description: Calendar dimension

    columns:
      - name: d
        tests:
          - unique
          - not_null

      - name: calendar_date
        tests:
          - unique
          - not_null